### ISSUE TITLE
Can't run with Pi Pico

### ISSUE THREAD

**Issue by educ8s** [benevpi/Circuit-Python-Gauge#1]
Hello, first of all thanks for the nice library.

It won't work out of the box. In the gauge.py file is this argument really needed?

super().__init__(max_size=20)

Without it it works.

Thanks

**Comment by benevpi** [comment]
Honestly, no idea.

I haven't used this for quite a long time and I think the displayio module
it uses might have changed a bit since then. Not sure I have a display that
works with Circuit Python that will plug into a Pico, but I'll have a dig
around and see what I can find to test out. If it's working for you without
it, leave it out :)

What error is it throwing if it does have that argument?

 Ben

**Comment by educ8s** [comment]
Thanks for the quick reply. I get this error:

Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "gauge.py", line 13, in __init__
TypeError: extra keyword arguments given

Without the argument works great.

I just a warning that I can easily fix in line 31. 
self.data = Label(terminalio.FONT, text="0.0", color=0xFFFFFF, max_glyphs=10)
max_glyph is no longer required.

Since I am new to github, what is the proper way to make my own version of this library, change it, extend it in some areas, giving you the proper credit for your work so far?

Thanks

**Comment by benevpi** [comment]
Ah yes, looks like it's just a case of them changing the arguments in the
displayio library. If you want to make a pull request of your fixes, I'll
bring it in otherwise it'll have to wait until I can dig out some hardware
to test on.

Ben

**Comment by educ8s** [comment]
Sure I can make a pull request, but I need to figure out how to do it. It will be my first ever pull.

Thanks for sharing this library,
Nick
